### ISSUE TITLE
API 500 Errors

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#11]
Console errors:
https://fom-10.apps.silver.devops.gov.bc.ca/public/projects
'''
zone.js:2863          GET https://fom-10.apps.silver.devops.gov.bc.ca/api/public-notice 500 (Internal Server Error)
'''

Visting API returns 500:
https://fom-10.apps.silver.devops.gov.bc.ca/api/response-code
'''
{"statusCode":500,"message":"Internal server error"}
'''

(Note: This seems to be working better in docker-compose.)

**Comment by ianliuwk1019** [comment]
As seen in today's session with Basil, the cause was the migration scripts were not found during startup.
Basil has suggested to adjust both 'ormconfig-migration-main.ts/ormconfig-migration-test.ts' configuration files so that it looks for the correct path for the migration scripts during migration (currently during deployment, the copied scripts are under '/dist/').

**Comment by DerekRoberts** [comment]
https://github.com/bcgov/nr-fom/pull/15
