### ISSUE TITLE
Missing ${ENV} in notification emails

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-fom#193]

**Comment by basilv** [comment]
Looked into this issue and found the following:
1. To test, just need to finalize a FOM. This sends the email (no need to run FOM batch).
2. We have logic for test environment to ensure all emails send to FLNR.AdminServicesCariboo. For prod, the emails are sent to the district office. For other environments (originally dev), the emails come to me (basil). This means for the demo environment I would get the emails as well.
3. Current logic (in main branch): in mail.service.ts sendDistrictNotification - retrieve environment variable ENV and uses it in prefix of subject, even for production. There's logic to default to 'dev' if not specified, but I don't think this worked.

**Comment by basilv** [comment]
Ah, I think because the template supplied ${ENV} and ENV wasn't defined, the env variable got the value ${ENV} which skipped the defaulting. So the change to supply ${ZONE} should work. The only outstanding item is we should decide whether I should still get the emails for the demo environment, or perhaps change this to Anne-Marie?

**Comment by basilv** [comment]
I raised #198 for an enhancement to email that includes the demo environment changing who gets these emails.
