### ISSUE TITLE
Button label for add / edit Online Public Notice

### ISSUE THREAD

**Issue by amee99073** [bcgov/nr-fom#253]
In Test - search for FOM at Initial Status
For FOM 100205 select View FOM
The button reads Add Online Public Notice.
Click on the Add Online Public Notice button and the public notice actually exists - .

**Expected Behaviour**
The Online Notice button should say Edit Online Public Notice, not Add Online Public Notice if the Online Public Notice exists

**Actual Behaviour**
The Online Notice button says Add Online Public Notice if the Online Public Notice exists for an Initial FOM

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. In Test - search for FOM at Initial Status
2. For FOM 100205 select View FOM
3. The button reads Add Online Public Notice.
4. Click on the Add Online Public Notice button and the public notice actually exists.
5. Also happens for 100082, 100200
6. 100243 shows Edit Online Public Notice as it should.
 
**Screenshots**
![image.png](https://images.zenhubusercontent.com/62019941f5a3b6cab303ec02/3328a856-f6d3-401f-b6c8-442c618cb243)
![image.png](https://images.zenhubusercontent.com/62019941f5a3b6cab303ec02/2b62d926-4a0f-49b6-98b1-f4f75d262546)

**Desktop (please complete the following information):**

 - Browser Edge, Chrome

**Comment by ArogeG** [comment]
@amee99073 does it make a difference that when you click on "Add Online Public Notice" button and edit or save the notice, the button changes to "Edit Online Public Notice"? For https://fom-test.nrs.gov.bc.ca/admin/a/100205, the End Operations field was empty, added a year and saved the notice and the button updated to "Edit Online Public Notice" @ianliuwk1019

**Comment by amee99073** [comment]
@ArogeG If I go back without saving it does not
IF I save (without changing any values) and return, it changes - see 100200
@ianliuwk1019

**Comment by ianliuwk1019** [comment]
I verified in TEST environment and confirm this isn't a bug but a **expected behavior**.

What happens is, the FOM which shows button "**Add** Online Public Notice" does indeed have no Public Notice associated with it. When the user clicks the "**Add**" button and steps into the input form (for Public Notice) **the admin frontend pulls the _latest Public Notice_ from database for this particular _Forest_Client_ and feed the data by default for the input form**.

This is verified on TEST (at the time FOM-100162 did not have Public_Notice):
![TEST_admin_publicNotice_FOM100162.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/6857b3d8-7296-457e-aca2-33e5f1aca26a)

![TEST_admin_publicNotice_FOM100162_no_publicNotice.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/5c59e05c-bdb6-4cbd-84af-d3cc136242d6)

![2022-09-28 13_42_19-fom-test-db-195-sgx8j · Details · KAMLOOPS SILVER CLUSTER.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/2d25f187-5f5b-4fae-acf3-f8342130e2f8)

![TEST_admin_publicNotice_FOM100162_pull_publicNotice_for_forestClient.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/d4055c24-773d-4348-ad96-c9d25b2caa25)

@ArogeG @amee99073 @basilv

**Comment by amee99073** [comment]
This makes sense when it's about the addresses - I wonder if this still holds true with the dates. I'll warn Julius via email. Thank you @ianliuwk1019

**Comment by ianliuwk1019** [comment]
Slight change today at frontend to conditionally remove operation dates when pulling previous public notice for the forest client to the input form.
This has been deployed to TEST environment today and informed Anne-Marie.

**Comment by ianliuwk1019** [comment]
Anne-Marie reported on Friday (after deployment to TEST) the 'save' for the public notice on input form does not work for operations years fields, everything else did get saved.
The pr that gets deployed to TEST has code change only in 'admin'. And the issue in TEST described above is unrelated to the code change (issue was in 'api').

Initial investigation was done on Friday after Anne-Marie reported, but could not find good reason why the deployment did not work for the new code change (on 'admin') and 'api' backend did not save operation years in database. I have checked the database columns for new fields are there in TEST (OpenShift), the fields shows up at frontend ('admin') in TEST, the http request sent correct years for both fields I selected in TEST to backend, the remaining component is why backend isn't saving the values selected while columns are there and are always empty after saving.... does not make any sense....

I conducted a subsequent PR that contains nothing change in each component (public/admin/api) and just a dummy space removal in code change in each component with Anne-Marie's help to approve and merge this dummy pr to 'main' branch. After deployment Anne-Marie did a test and pass her expectation. Everything now is good in TEST.

This is a strange behavior in Openshift deployment (or maybe from github action?). Something funny is going on. It might need Derek's assistance to look deeper in this issue. I feel, with only code change in only one component (in this case 'admin), some other components (in this case the issue component 'api) does not seem to keep the latest code/image for the deployment and out of sync.

Interesting note related to this issue (and happened in earlier vulnerability pr): Anne-Marie observed that the pr's TEST deployment did not even have operation years fields in 'admin' page, although nothing was changed to code but the package.json in 'api' component. However, due to later there was one more pr needed that day to correct the code at 'admin' TEST was being deployed again and we saw the operation year fields show up again in 'admin'.

@ArogeG @basilv @amee99073
