### ISSUE TITLE
FOM Back-end: Integration with FAM

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fom#280]
Change FOM API back-end decryption of JWT token to use FAM certificate.
Change FOM API back-end parsing of JWT token.

**Comment by ianliuwk1019** [comment]
Frontend task #47 is mostly done which mainly focuses on frontend using Aws-Amplify lib to handle site redirect to common authentication login and also logout. 
This unblock for backend integration with frontend as backend needs token passing to backend (either real token or fakeUser previously setup for FOM).

From then I will handle the code merge, code clean-up, refactoring (if necessary), and frontend-backend integration overall verification, pr creation and addressing Basil's review comments and some environment setup during deployment.

Currently I resolved frontend admin not building properly issue. Fixed fakeUser (local development purpose) User object token backend interpretation issue.

Trying to figure out real token (Cognito access token) verification problem (token is different than Keycloak.

**Comment by ArogeG** [comment]
@ArogeG to test the front-end once this ticket is complete

**Comment by ianliuwk1019** [comment]
Just a reminder from Catherin not to forget to do this: "update the redirect logout url to include the logout chain in the config map".

**Comment by ianliuwk1019** [comment]
Current strange issue:
Locally, FOM frontend/backend for FAM integration works.
However, for FOM Dev deployment (Opennshift), we are encountering strange infinite loop for login due to Amplify cannot get the authenticated user.
From the network traffic and debug level (Amplify) console, it seems the handshake for Amplify with Cognito is done but somehow the internal (authentication) information for Amplify is lost after redirect back to the user's browser and triggers another login. We still haven't figured it out what causes this issue...

**Comment by ianliuwk1019** [comment]
The issue for FOM infinite login loop is identified and resolved.
There was a suspicious network traffic spotted after Cognito returns to 'redirectSignIn' url that in comparison to a good login scenario, http status:200, it got http status:302. See below:
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/e5feaa86-91ff-4893-a08c-4a98636ba91a)
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/6d01eecf-d05a-458e-98a0-13d592ce58fa)

The query parameter at the url (?code=53b9dd78-....) exists in both. This seems to be the authorization code given by Cognito during the auth handshake with Amplify and somehow Amplify lost the code from the problem screen. Also from the problem screen, we can also see  it redirect to "admin/" next.

This is a good indication that since FOM frontend is deployed at Openshift with "Caddy" webserver in between, it is likely something to do with Caddy. By examing Caddyfile (configuration for Caddy at 'admin') it has this:
![image.png](https://images.zenhubusercontent.com/62a9ff93d8506f14758ef03a/602d01bf-7771-4732-a7b0-2beb5de54817)
Looks to me (not a reverse proxy server expert but got a feeling) that Caddy might stripped out the query parameters when doing redirect at ("/admin"), however, I could not find in Caddy doc if that's true but almost certain. Configuring Caddy file is quite tricky but still spent some hours to see if it can be done, but then no successful result.

In the process of configuring Caddy, I also realized the Cognito 'redirectSignIn' is actually the base url and is corresponding to this (redir "/admin") in Caddy and we do have an Angular route for signin landing page different than base url (/admin/search). So by coding this in the 'redirectSignIn' as "/admin/search", which should be the correct one from previous FOM code as the landing page after user sign in, is the right solution instead of tweaking Caddy configuration.

**Comment by ianliuwk1019** [comment]
Frontend was having a tricky issue with un-authorized Angular page being loaded about 1~2 seconds before redirect browser to Cognito sign in page.
This issue is resolved now. In short, initializing Amplify before redirect is slower than Angular load up and the route goes to first route page (un-authorized page). Angular Service (Cognito Service) was configured in Angular's APP_INITIALIZER first during startup but still slow. Discovered that it is due to Cognito service "promise" (during init() ) was "resolved" too quick before redirect happens. To fix this problem, we don't need to return a "resolve" since Amplify signin() is called first and will eventually redirect to Cognito.

Now, start working on cleaning up for unused keycloak and sitemider code.

**Comment by ianliuwk1019** [comment]
PR #287 contains all code (frontend/backend) and cleanup changes #320 plus Basil's PR #318 as well together and merged to FOM's main branch and deployed to TEST environment.
Currently is waiting for FAM to have the redirect url fixes for this client deployed into PROD.

**Comment by ianliuwk1019** [comment]
These are the client status from "Forest Client API":
```
ACT (Active)
DAC (Deactivated)
DEC (Deceased)
REC (Receivership)
SPN (Suspended)
```
* FAM backend will return to FAM frontend with mapping of client status codes (from Forest Client API) with: "**`Active (Active)`**" and "**`Inactive (Inactive) - Deactivated, Deceased, Receivership, Suspended`**".
* For the **"backend"** validation before saving user-role assignment, I assume only the "exists forest client with Active status" can be granted for access. However, curious if current "bulk users role assignment imported from the script include all other client status other than Active" and will this "Active" status restriction affects the script import. #481
* Won't check "**client type**" before saving, since all types are valid including "individuals", see comment from #179. 
@basilv @ArogeG

**Comment by ArogeG** [comment]
FOM looks to be working as expected with both submitter and reviewer roles on FAM
