### ISSUE TITLE
Enable mouse scroll zoom-in and out on the map on the "details page"

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-fom#493]
**Describe the Bug**
Enable zoom-in and out on the map on the "details page" (in the public portal).

Mouse scroll to zoom-in and out works on the map on the main page but not on the map on the "details page". 

<img width="1362" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTQ2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02359d39372d1cf4a25b2b739be552f06ccf0247/Capture-fom-bug.PNG" alt="Capture-fom-bug.PNG" />

**Comment by OlgaLiber2** [comment]
@ianliuwk1019 FYI

**Comment by ianliuwk1019** [comment]
Both **Admin** and **Public** details map (on public, it is at the "**Details**" panel within specific FOM) are working for the mouse scroll zoom. 

However, the way it works is, the user needs to **click** on map (using the mouse) "first" before it enables the scrolling. The reason is probably that it is not desirable to interfere outer scroll bar when the user is meant to scroll the page, not to zoom to the map when the mouse happen to be on the map area.

For the public "**Big**" map (since it occupies the whole page), it is automatically default (without needing to **click** enable) and user can scroll.

Do we want to change this behavior for "Details" map?
@OlgaLiber2 @basilv

**Comment by ianliuwk1019** [comment]
After discussion, seems having the same behavior like the one on public "Big" map is desirable. I will adjust the default setting for both admin/public.

**Comment by ianliuwk1019** [comment]
Done, merged and deployed to FOM TEST:
https://fom-test.nrs.gov.bc.ca/public/projects#splash
https://fom-test.nrs.gov.bc.ca/admin/
@OlgaLiber2 @gormless87

**Comment by OlgaLiber2** [comment]
@ianliuwk1019  looks good, thanks.
