### ISSUE TITLE
Find out who can create an FSP API for us 

### ISSUE THREAD

**Issue by OlgaLiber2** [bcgov/nr-fom#495]
Find out from Michelle who can create an API for us from the team that owns data , the Forest Stewardship Plan data "FSP ID"
- probably in FSP tacker

AC: 
- find out who owns the data
- after we know who owns the data, contact them to create an API

**Comment by basilv** [comment]
Email sent to Michelle to understand options.

**Comment by basilv** [comment]
The discussion below highlights some of the options. Probably the 'best' is to use the nr-oracle-service, stand it up in the FOM OpenShift namespace, and then use it to get access to the FSP table and issue queries against this table via the API provided by this service.

nr-oracle-service option:

https://github.com/bcgov/nr-oracle-service

From Om:
since nr-oracle-service is HELM chart, that can be deployed easily without the hassle of coding, and maintaining.

Connectivity to Oracle from Zone B exists for hosts and is available on 1543 port, which the nr-oracle-service uses and connects over TCPS.

For Authorization, each proxy account in oracle would have access to specific objects.

The nr-oracle-service(API Key Security in place) can be hooked up with API gateway to be consumed outside of OpenShift namespace.

Basil's response:

Thanks Om. I missed the part where nr-oracle-service is already existing, I thought it was hypothetical (missed the github link :). Okay, so FOM would have to spin up this nr-oracle-service, and we’d need a Oracle account with access to e.g. FSP table. That seems fairly workable. It doesn’t address the lack of a centralized API for these foundational data elements – e.g. FOM becomes dependent upon the structure of the THE schema as we’re essentially issuing SQL queries through the API, instead of having a common API encapsulate access to particular data sets like FSPs. So it seems like it would be a short-term tactical solution for FOM, but doesn’t help progress on the longer term problem of reducing direct dependencies on the monolith database.

**Comment by basilv** [comment]
Other option was using a spatial layer for FSPs, but this seemed to be messy. Some of the layers proposed seemed to have multiple objects for one FSP, and some of the objects are quite large (spatially).

From Annika Livingston:
I wonder in the FDU datasets includes the FSP’s as it describes “The spatial representation of a Forest Stewardship Plan and Forest Development Units. “

From Michelle: 
Perhaps FDU is the right one? As Annika referred too.. 
[https://openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_FOREST_TENURE.FSP_FDU_POLY_SPG&outputFormat=text%2Fjavascript&format_options=callback%3AgetJson&SrsName=EPSG%3A4326&PROPERTYNAME=FSP_ID&CQL_FILTER=FSP_ID%3D24&callback=getJson&_=1525714041640](https://urldefense.com/v3/__https:/openmaps.gov.bc.ca/geo/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_FOREST_TENURE.FSP_FDU_POLY_SPG&outputFormat=text*2Fjavascript&format_options=callback*3AgetJson&SrsName=EPSG*3A4326&PROPERTYNAME=FSP_ID&CQL_FILTER=FSP_ID*3D24&callback=getJson&_=1525714041640__;JSUlJQ!!AaIhyw!si9YWwQaxWqGM2qPjRrxcxzg4EijH2wpcl3uzNyWsMxKDjUzaQUYhnmRXttlO_lqdlZzi36NFV7joH8RDXiW4zYrcnBazXmD-Q$) 

This is an ugly layer of overlapping polygons: even with the generalized layer – each polygon is quite large in the WFS service – I pulled back one polygon with an WFS call and it was 16mb..
[https://webgismd.github.io/lf-wms-wfs/lfg/lfwmsi.html?l=WHSE_FOREST_TENURE.FSP_FDU_POLY_SPG&a=FSP_ID&f=FSP_ID%3D137](https://urldefense.com/v3/__https:/webgismd.github.io/lf-wms-wfs/lfg/lfwmsi.html?l=WHSE_FOREST_TENURE.FSP_FDU_POLY_SPG&a=FSP_ID&f=FSP_ID*3D137__;JQ!!AaIhyw!si9YWwQaxWqGM2qPjRrxcxzg4EijH2wpcl3uzNyWsMxKDjUzaQUYhnmRXttlO_lqdlZzi36NFV7joH8RDXiW4zYrcnCR-BvdIg$)

**Comment by webgismd** [comment]
What is the query and output you are hoping to get out of a FSP API? 
@basilv

**Comment by basilv** [comment]
We just need the list of FSPs (id + name) to validate the FSP within FOM and display the name instead of just the FSP ID.
So the query would likely just be something like "select id, name from fsp" (I don't know the exact table/column names :)
