### ISSUE TITLE
Separate Admin-Frontend

### ISSUE THREAD

**Issue by gormless87** [bcgov/nr-fom#52]

**Comment by ianliuwk1019** [comment]
Just some reference after figuring out build issue for 'admin':

Initial build for new 'admin' had some errors not seen from previous 'public' build.
For example, something like this:
`
/foms/fom-submission/fom-submission.component.html: 100:85 - error TS2339: Property 'count' does not exist on type 'SubmissionDetailResponse'.    
	
   100    <span class="name">Cut block submission - {{spatialSubmission.cutblocks.count}} blocks</span>
`
`
Error: src/app/foms/review-comments/review-comments.component.html:21:54 - error TS2339: Property 'length' does not exist on type 'unknown'.

	21     <h2 style="margin: 0;">Comments ({{data?.length}})</h2>
       
	=> Most error happens on array[]. For some reason, the array is type of 'unknown' thus it could not see the property 'length'.
`	   
After some digging, it seems to be related to additional Type checking set in tsconfig.json at 'angularCompilerOptions' for the flag '**"strictTemplates": true**'.

According to [Angular documentation](https://angular.io/guide/angular-compiler-options#stricttemplates), this is included by default for newly created Angular project for good to have option. 

From what I see our FOM project was migrated from previous version Angular (probably Angular 6) to Angular 11. This flag to my best knowledge, wasn't included that time when it was under mono-repo and the build works fine.
I tried without the flag and it could be built without this good-to-have compile option. I will ignore (remove) this flag for now. Note, 'public' does have this flag (wasn't included previously at mono-repo) but does not have build issue so far (perhaps because public is simple enough).
We could include this flag in the future but some source code will need to be fixed accordingly.
