### ISSUE TITLE
Production: BCGW Replication Starting To Fail

### ISSUE THREAD

**Issue by ianliuwk1019** [bcgov/nr-fom#624]
**Describe the Bug**
BCGW reported their midnight replication jobs continue to fail and also fail on manual re-run as well.
They have provided summary report for these few days as follow:
![image](https://github.com/bcgov/nr-fom/assets/81595625/02772a96-a44e-4028-8803-cc189f92ae6a)

When verified on "May 02" for api log on Kibana, log entries indicates all morning midnight 3 runs were all finished. Something else might have failed to return BCGW the query result.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. ...
**Screenshots**

**Additional context**
API endpoint:   @Get('/bcgw-extract')

**Comment by MCatherine1994** [comment]
- Update our cron job for `workflow state code update' to 1 hour earlier (1am PST, use 8am UTC), so it won't run at the same time as the BCWG extract
- Increate the API requested/limit memory
- Ask if BCGW team has a default time out on their api as well

**Comment by MCatherine1994** [comment]
From FOM PROD API memory matrix, we did see at some peak time, the memory usage is way more than we requested now (currently is 140M)

![Image](https://github.com/bcgov/nr-fom/assets/23131735/a073b457-9c95-453d-870e-34f5500f0c02)

![Image](https://github.com/bcgov/nr-fom/assets/23131735/89ecd734-d2a8-4d50-bca0-edf5d36c0f8f)

![Image](https://github.com/bcgov/nr-fom/assets/23131735/b18a5ebf-3797-490d-b1b5-59ad0dfc1c4b)

Will increate the requested memory to 600M to guarantee the usage. Because in the case the usage exceeds our requested value, even though it's not exceeding the limit value, but if we can't borrow more resource from other container, it will fail. 
![Image](https://github.com/bcgov/nr-fom/assets/23131735/c4329bed-3721-454c-8d0a-b889c8b27697)


Out of memory error from Kibana:

![Image](https://github.com/bcgov/nr-fom/assets/23131735/ac0d41e9-c769-4c61-8743-a1d98744b9c7)

![Image](https://github.com/bcgov/nr-fom/assets/23131735/17383d35-1125-41c0-98a4-c26aead81043)


The running time for the BCGW extract is up to 80s for now, still within our limit (120s), but because of the run out of memory error, the app might be restarted, that's why it didn't return the result back

![Image](https://github.com/bcgov/nr-fom/assets/23131735/ee01e886-22a9-492e-846e-70e0c0727a46)

![Image](https://github.com/bcgov/nr-fom/assets/23131735/2c886d63-131c-42b9-8e2f-fad6deba850a)

![Image](https://github.com/bcgov/nr-fom/assets/23131735/dd0c9c01-2bc7-44f7-a02e-a18979fc2836)




Reference: [How to setup Kibana to check logs](https://stackoverflow.developer.gov.bc.ca/questions/906/907#907)
